export const LAUNCH_LINK_STATE = 'LAUNCH_LINK_STATE';
export const LAUNCH_PAGE_STATE = 'LAUNCH_PAGE_STATE';

export const AUTH_USER = 'AUTH_USER';
export const TAG_INCOMPLETE_USER = 'TAG_INCOMPLETE_USER';
export const UN_AUTH_USER = 'UN_AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';



export const GET_CLASSIFICATION_TAG_DATA = 'GET_CLASSIFICATION_TAG_DATA';
export const SAVE_CLASSIFICATION_TAG_DATA = 'SAVE_CLASSIFICATION_TAG_DATA';
